ampOnIcon = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
.....5c.......................
]]

ampOffIcon = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
...x.5c....y.......z..........
]]

-- caffeine replacement

local module = {}

local function setIcon(state)
  module.menu:setIcon(state and ampOnIcon or ampOffIcon)
end

function module:init()
  print("Initializing Amphetamine")
  module.menu = hs.menubar.new()
  module.menu:setClickCallback(function() setIcon(hs.caffeinate.toggle("displayIdle")) end)
  setIcon(hs.caffeinate.get("displayIdle"))
end

return module
